// This file was auto-generated by ML.NET Model Builder. 

using System;
using Laughing_enigmaML.Model;

namespace Laughing_enigmaML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                BoxRatio = 0.6687F,
                Thrust = 0.0911F,
                Velocity = -1.0402F,
                OnBalRun = -0.0232F,
                VwapGain = -0.9291F,
                Altitude = 0F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Acceleration with predicted Acceleration from sample data...\n\n");
            Console.WriteLine($"BoxRatio: {sampleData.BoxRatio}");
            Console.WriteLine($"Thrust: {sampleData.Thrust}");
            Console.WriteLine($"Velocity: {sampleData.Velocity}");
            Console.WriteLine($"OnBalRun: {sampleData.OnBalRun}");
            Console.WriteLine($"VwapGain: {sampleData.VwapGain}");
            Console.WriteLine($"Altitude: {sampleData.Altitude}");
            Console.WriteLine($"\n\nPredicted Acceleration: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
