// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Laughing_enigmaML.Model
{
    public class ModelInput
    {
        [ColumnName("BoxRatio"), LoadColumn(0)]
        public float BoxRatio { get; set; }


        [ColumnName("Thrust"), LoadColumn(1)]
        public float Thrust { get; set; }


        [ColumnName("Acceleration"), LoadColumn(2)]
        public float Acceleration { get; set; }


        [ColumnName("Velocity"), LoadColumn(3)]
        public float Velocity { get; set; }


        [ColumnName("OnBalRun"), LoadColumn(4)]
        public float OnBalRun { get; set; }


        [ColumnName("vwapGain"), LoadColumn(5)]
        public float VwapGain { get; set; }


        [ColumnName("Altitude"), LoadColumn(6)]
        public float Altitude { get; set; }


    }
}
